export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_USER = 'SET_USER';
export const SPECIAL_MESSAGE_SHOW = 'SPECIAL_MESSAGE_SHOW';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const UPGRADE_CREATE = 'UPGRADE_CREATE';
export const UPGRADE_CREATE_SUCCESS = 'UPGRADE_CREATE_SUCCESS';


export const RESOURCE_LIMIT_SHOW = 'RESOURCE_LIMIT_SHOW';
