export const CHANGE_THEME = 'CHANGE_THEME';
export const SET_USER = 'SET_USER';
export const SPECIAL_MESSAGE_SHOW = 'SPECIAL_MESSAGE_SHOW';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const IMPORT_CHANGE_MAPPING = 'IMPORT_CHANGE_MAPPING';
export const IMPORT_RESET_MAPPING = 'IMPORT_RESET_MAPPING';
export const IMPORT_CHANGE_DATA = 'IMPORT_CHANGE_DATA';

export const RESOURCE_LIMIT_SHOW = 'RESOURCE_LIMIT_SHOW';
